### ISSUE TITLE
org.jetbrains.kotlin.gradle.plugin.PLUGIN_CLASSPATH_CONFIGURATION_NAME not being resolved

### ISSUE THREAD

**Issue by brookmg** [jisungbin/KotlinCompilerPluginSample#2]
I am experiencing an error trying to sync Gradle after editing this. I'm using Groovy and not kts for the configurations. 

```
Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method PLUGIN_CLASSPATH_CONFIGURATION_NAME() for arguments [DefaultProjectDependency{dependencyProject='project ':localization-kcp'', configuration='default'}] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

**Comment by jisungbin** [comment]
Hi, thanks for sharing your issue. Could you try the "kotlinCompilerPluginClasspath" configuration? The `org.jetbrains.kotlin.gradle.plugin.PLUGIN_CLASSPATH_CONFIGURATION_NAME` constant hardcodes "kotlinCompilerPluginClasspath".

```groovy
dependencies {
  add("kotlinCompilerPluginClasspath", YOUR_KOTLIN_COMPILER_PLUGIN_MODULE)
}
```

If the above doesn't work, Groovy will need to use a different `import`.

```groovy
import org.jetbrains.kotlin.gradle.plugin.KotlinPluginKt

...

dependencies {
  add(KotlinPluginKt.PLUGIN_CLASSPATH_CONFIGURATION_NAME, YOUR_KOTLIN_COMPILER_PLUGIN_MODULE)
}
```

**Comment by brookmg** [comment]
Now I'm getting `Caused by: org.gradle.api.artifacts.UnknownConfigurationException: Configuration with name 'kotlinCompilerPluginClasspath' not found.` exception. 

Somethings to mention, I'm working on an Android project and here are the current versions for 
* com.android.tools.build:gradle - 8.0.1
* org.jetbrains.kotlin:kotlin-gradle-plugin - 1.8.21

------------------------------------------------------------
Gradle 8.0
------------------------------------------------------------

Build time:   2023-02-13 13:15:21 UTC
Revision:     62ab9b7c7f884426cf79fbedcf07658b2dbe9e97

Kotlin:       1.8.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          1.8.0_362 (Private Build 25.362-b09)
OS:           Linux 5.19.0-43-generic amd64

**Comment by jisungbin** [comment]
@brookmg Did you add the Kotlin plugin to that Gradle file?

```groovy
apply plugin: 'org.jetbrains.kotlin.jvm'
// or
apply plugin: 'org.jetbrains.kotlin.android'
```

The `kotlinCompilerPluginClasspath` configuration is initialized when the Kotlin plugin is applied.

**Comment by brookmg** [comment]
Yap thank you, got it. I must define the plugin for the specific module with the kotlin plugin configured and not on the root build.gradle. It worked when I moved the dependency to the build.gradle under app.
